// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxbscxkngniqnhknhvsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4YnNjeGtuZ25pcW5oa25odnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzYwNTksImV4cCI6MjA2NjkxMjA1OX0.9zQAZ5eyyOKXc1ZvkwcFxC4rvjoRR4SbuOZlgsZPP2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});